# Generated by Django 2.2 on 2019-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_page_projet_img_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_projet',
            name='img_description',
            field=models.ImageField(default='static/images/desciption_projet/no-img.jpg', upload_to='static/images/description_projet/'),
        ),
    ]
