# Generated by Django 2.2 on 2019-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190414_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_projet',
            name='img_description',
            field=models.ImageField(default='media/book/desciption_projet/no-img.jpg', upload_to='media/book/description_projet/'),
        ),
    ]
