# Generated by Django 2.2 on 2019-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190414_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_projet',
            name='img_description',
            field=models.ImageField(default='static/images/description_projets/no-img.jpg', upload_to='static/images/description_projets/'),
        ),
    ]
