# Generated by Django 2.2 on 2019-04-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190414_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curivitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('poste_descrip', models.TextField()),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
