# Generated by Django 2.2 on 2019-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_curivitae'),
    ]

    operations = [
        migrations.AddField(
            model_name='curivitae',
            name='entreprise',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
