# Generated by Django 2.2 on 2019-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_curivitae_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curivitae',
            name='poste_descrip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page_projet',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
